service: empape
runtime: python37
entrypoint: gunicorn -t 120 -b :$PORT run:app

instance_class: F1

env_variables:
  PROJECT_ID: 'empape'
  DATA_BACKEND: 'cloudsql'
  CLOUDSQL_USER: 'root'
  CLOUDSQL_PASSWORD: ''
  CLOUDSQL_DATABASE: 'empape'
  CLOUDSQL_CONNECTION_NAME: 'thinger:us-east1:empape'